# Generated by Django 5.1.1 on 2024-10-03 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название породы')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Кличка котенка')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет котенка')),
                ('age_in_months', models.PositiveIntegerField(verbose_name='Возраст котенка (полных месяцев)')),
                ('description', models.TextField(verbose_name='Описание котенка')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Общее количество голосов')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.breed', verbose_name='Порода')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Котенок',
                'verbose_name_plural': 'Котята',
            },
        ),
    ]
