# Generated by Django 5.1.1 on 2024-10-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitten',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kitten',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
